name = "hemifuture-landing"
account_id = "8bafdbd1f2d967917dbc0a67156266fa"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"]
# main = "dist/_worker.js/index.js"

[assets]
directory = "./dist"